use anyhow::{Context, Result};
use std::fs;
use std::io::{self, Write};
use std::path::PathBuf;

/// Get the global AgentMem config directory
pub fn get_global_config_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".agentmem")
}

/// Get the credentials file path
pub fn get_credentials_path() -> PathBuf {
    get_global_config_dir().join("credentials")
}

/// Get API credentials from environment or credentials file
pub fn get_api_credentials() -> Result<Option<String>> {
    // First check environment variable
    if let Ok(key) = std::env::var("AGENTMEM_API_KEY") {
        if !key.is_empty() {
            return Ok(Some(key));
        }
    }

    // Then check credentials file
    let creds_path = get_credentials_path();
    if creds_path.exists() {
        let content = fs::read_to_string(&creds_path)?;
        for line in content.lines() {
            if line.starts_with("AGENTMEM_API_KEY=") {
                let key = line.strip_prefix("AGENTMEM_API_KEY=").unwrap_or("");
                if !key.is_empty() {
                    return Ok(Some(key.to_string()));
                }
            }
        }
    }

    Ok(None)
}

/// Get user ID from credentials file
pub fn get_user_id() -> Result<Option<String>> {
    let creds_path = get_credentials_path();
    if creds_path.exists() {
        let content = fs::read_to_string(&creds_path)?;
        for line in content.lines() {
            if line.starts_with("AGENTMEM_USER_ID=") {
                let id = line.strip_prefix("AGENTMEM_USER_ID=").unwrap_or("");
                if !id.is_empty() {
                    return Ok(Some(id.to_string()));
                }
            }
        }
    }
    Ok(None)
}

/// Get machine ID (stable identifier for this machine)
pub fn get_machine_id() -> String {
    // Try to get from credentials file first
    if let Ok(Some(id)) = get_stored_machine_id() {
        return id;
    }

    // Generate a new one based on hostname
    let hostname = hostname::get()
        .map(|h| h.to_string_lossy().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    format!("{}-{}", hostname, &uuid::Uuid::new_v4().to_string()[..8])
}

fn get_stored_machine_id() -> Result<Option<String>> {
    let creds_path = get_credentials_path();
    if creds_path.exists() {
        let content = fs::read_to_string(&creds_path)?;
        for line in content.lines() {
            if line.starts_with("AGENTMEM_MACHINE_ID=") {
                let id = line.strip_prefix("AGENTMEM_MACHINE_ID=").unwrap_or("");
                if !id.is_empty() {
                    return Ok(Some(id.to_string()));
                }
            }
        }
    }
    Ok(None)
}

/// Save API credentials to file
pub fn save_credentials(api_key: &str, user_id: &str, email: &str) -> Result<()> {
    let config_dir = get_global_config_dir();
    fs::create_dir_all(&config_dir)?;

    let creds_path = get_credentials_path();

    // Get or generate machine ID
    let machine_id = get_stored_machine_id()?.unwrap_or_else(get_machine_id);

    let content = format!(
        "# AgentMem Credentials\n\
         # Generated by 'am auth login'\n\
         \n\
         AGENTMEM_API_KEY={}\n\
         AGENTMEM_USER_ID={}\n\
         AGENTMEM_EMAIL={}\n\
         AGENTMEM_MACHINE_ID={}\n",
        api_key, user_id, email, machine_id
    );

    fs::write(&creds_path, content)?;

    // Set permissions to user-only on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&creds_path)?.permissions();
        perms.set_mode(0o600);
        fs::set_permissions(&creds_path, perms)?;
    }

    Ok(())
}

/// Clear saved credentials
pub fn clear_credentials() -> Result<()> {
    let creds_path = get_credentials_path();
    if creds_path.exists() {
        fs::remove_file(&creds_path)?;
    }
    Ok(())
}

/// Prompt user for API key
pub fn prompt_api_key() -> Result<String> {
    print!("Enter your API key: ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let api_key = input.trim().to_string();

    if !api_key.starts_with("am_") {
        anyhow::bail!("Invalid API key format. Keys should start with 'am_'");
    }

    Ok(api_key)
}

/// Prompt user for email (for registration)
pub fn prompt_email() -> Result<String> {
    print!("Enter your email: ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let email = input.trim().to_string();

    if !email.contains('@') {
        anyhow::bail!("Invalid email format");
    }

    Ok(email)
}

/// Check if user is authenticated
pub fn is_authenticated() -> bool {
    get_api_credentials().ok().flatten().is_some()
}
